# Generated by Django 2.2.16 on 2020-10-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('organisation', models.CharField(blank=True, default='', max_length=1000)),
                ('phone', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
