# Generated by Django 3.1.2 on 2020-10-31 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='address',
            new_name='bio',
        ),
    ]
