# Generated by Django 2.2.16 on 2020-10-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201031_1256'),
        ('app', '0003_opensourcepost'),
    ]

    operations = [
    ]
