# Generated by Django 2.2.16 on 2020-11-01 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201031_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opensourcepost',
            name='last_date',
        ),
    ]
