# Generated by Django 2.2.16 on 2020-11-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_opensourcepost_last_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opensourcepost',
            old_name='registration_link',
            new_name='github_link',
        ),
    ]
